stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - ${dirs.dataset}
    outs:
      - ${dirs.outputs.preprocess}
    params:
      - preprocess

  train:
    cmd: python scripts/train.py
    deps:
      - ${dirs.outputs.preprocess}
    outs:
      - ${dirs.outputs.train}
    params:
      - train

  evaluate:
    always_changed: true
    cmd: python scripts/evaluate.py
    deps:
      - ${dirs.outputs.preprocess}
      - ${dirs.outputs.train}
    plots:
      - ${dirs.outputs.evaluate}/roc_curve.png
      - ${dirs.outputs.evaluate}/conf_matrix.png
    metrics:
      - ${dirs.outputs.evaluate}/metrics.json
    params:
      - evaluate

  mutamorphic_preprocess:
    cmd: python scripts/mutamorphic/preprocess.py
    deps:
      - ${dirs.dataset}/test.txt
    outs:
      - ${dirs.outputs.mutamorphic}/x_test.joblib

  mutamorphic_evaluate:
    always_changed: true
    cmd: python scripts/mutamorphic/evaluate.py
    deps:
      - ${dirs.outputs.train}/model.keras
      - ${dirs.outputs.mutamorphic}/x_test.joblib
      - ${dirs.outputs.preprocess}/y_test.joblib
    plots:
      - ${dirs.outputs.mutamorphic}/roc_curve.png
      - ${dirs.outputs.mutamorphic}/conf_matrix.png
    metrics:
      - ${dirs.outputs.mutamorphic}/metrics.json
    params:
      - evaluate