stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - ${dirs.dataset}
    outs:
      - ${dirs.outputs.preprocess}
    params:
      - preprocess

  train:
    cmd: python scripts/train.py
    deps:
      - ${dirs.outputs.preprocess}
    outs:
      - ${dirs.outputs.train}
    params:
      - train

  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - ${dirs.outputs.preprocess}
      - ${dirs.outputs.train}
    outs:
      - ${dirs.outputs.evaluate}/roc_curve.png
      - ${dirs.outputs.evaluate}/conf_matrix.png
    metrics:
      - ${dirs.outputs.evaluate}/metrics.json
    params:
      - evaluate

  # make_mutamorphic_data:
  #   cmd: python tests/mutamorphic_tests.py
  #   deps:
  #     - dataset/train.txt
  #   outs:
  #     - outputs/x_train_mutated.joblib
  # mutamorphic_eval:
  #   cmd: python tests/mutamorphic_eval.py
  #   deps:
  #     - outputs/model.h5
  #     - outputs/x_train_mutated.joblib
  #     - outputs/y_train.joblib
  #   outs:
  #     - outputs/mutamorphic_classification_report.csv
  #     - outputs/mutamorphic_confusion_matrix.png
  #     - outputs/mutamorphic_roc_curve.png
