name: Reproduce and run tests

on:
  push:
    branches: [main, fix-mutamorphic, code-quality]

jobs:
  Reproduce-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Lint (flake8)
        run: flake8

      - name: Lint (bandit)
        run: bandit -c pyproject.toml -r .

      - name: Lint (pylint)
        run: pylint scripts/ tests/ > pylint_report.txt

      - name: Generate pylint score chart
        run: python generate_chart.py

      - name: Commit and push chart
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add pylint_score.png
          git commit -m "Update Pylint score chart"
          git push

#      - name: Reproduce the pipeline
#        env:
#          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
#        run: |
#          dvc remote modify gdrive gdrive_use_service_account true
#          dvc pull
#          dvc repro
#          dvc metrics show
#
#      - name: Run tests
#        run: pytest